version: '3.8'
services:
  nuxtapp:
    build: .
    image: awnuxt
    ports:
      - '3999:3000'

  mongo-db:
    image: mongo
    ports:
      - '27017:27017'

  server:
    build: ./external_server
    image: node_backend
    volumes:
      - ./external_server:/app/
    ports:
      - '3001:3000'
    links:
      - mongo-db

  live-reloader:
    image: apogiatzis/livereloading
    container_name: livereloader
    privileged: true
    environment:
      - RELOAD_DELAY=1.5
      - RELOAD_CONTAINER=server
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ".:/app/"
